### ISSUE TITLE
Why consider the closed list like the openlist in function SearchStep?

### ISSUE THREAD

**Issue by shawee** [justinhj/astar-algorithm-cpp#11]
Your code really help me a lot but I have a question that in the SearchStep() method, why do you consider the closed list like the open list. In other word, I think when the successor is in the CLOSED list, we should ignore it directly, but you try " if node_successor is on the CLOSED list but the existing one is as good or better then discard this successor and continue ".

**Comment by justinhj** [comment]
I believe that corrects the situation that we find a new way to arrive at a node that we thought was not on the optimal path, but now maybe it is.
