### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by clovismarcondes** [justinhj/astar-algorithm-cpp#12]
Hi,

I made some improvements on this project and if you want to use some of them I can provide it. I had to do some experiments to analyze a new heuristic algorithm and so I implemented two different methods, one to generate the next state provided another state, and another one to generate a random() state. To avoid the usage of unsolvable states, I´ve created a method to check if the state is solvable or not. As I need to put the algorithm to execute several times I introduced a second argument with the number of repetitions and put all this in a loop. There are some modifications about the heuristics but it is related to my own experiments, but I can explain them if you wish.

**Comment by justinhj** [comment]
Can you send a pull request and I'll have a look at your changes?
