### ISSUE TITLE
IndexOutOfRangeException: FATAL - HexGrid has run out of preallocated MapSearchNodes! 80000>= 80000 

### ISSUE THREAD

**Issue by tangeping** [justinhj/astar-algorithm-cpp#20]
// Fixed sizes for collections
        readonly int kPreallocatedNodes = 80000;
        readonly int kPreallocatedMapSearchNodes = 80000;

I fixed the number of this, it's still have an error of “FATAL - HexGrid has run out of preallocated MapSearchNodes”。 what's wrong of it?

**Comment by justinhj** [comment]
Hi Tangeping
Is it possible your implementation is creating new nodes unbounded? You will eventually run out of free nodes if you do that.

**Comment by tangeping** [comment]
Hi justinhj
Thank you for your answer,I read your code, but it show me that it will loop step until find a successful path . and then the free nodes are constantly used. would you help me?

`            do
            {
                searchState = pathfinder.SearchStep();
                searchSteps++;
            }
            while (searchState == AStarPathfinder.SearchState.Searching);`

**Comment by justinhj** [comment]
No, there's no way to handle large maps without changing your data structure.
