### ISSUE TITLE
Bug in c# code

### ISSUE THREAD

**Issue by gorodovoy** [justinhj/astar-algorithm-cpp#24]
In c# code in AStarPathfinder.SortedAddToOpenList() field "inserted" is always "false".

**Comment by justinhj** [comment]
cc/ @ScaryG

**Comment by gorodovoy** [comment]
Second bug in C#.
---------------------------------------------------
In "GetSuccessors(...)" method instead
`NodePosition parentPos = new NodePosition(0, 0);`
we should use
`NodePosition parentPos = new NodePosition(-1, -1);`
Because (0, 0) is a **real** position on the map, and we can not use (0, 0) as position of **nonexistent** parent.

**Comment by justinhj** [comment]
Thank you @gorodovoy 
If you fix the other one we can close the issue :)

**Comment by justinhj** [comment]
Moved cs to a new repo, see readme. Closing this issue
